[package]
name = "ldraw-olr"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2021"

[dependencies]
cgmath = "~0.18.0"
glow = "~0.11.0"
glutin = "~0.27.0"
image = "~0.23.14"
ldraw = { path = "../ldraw" }
ldraw-ir = { path = "../ir" }
ldraw-renderer = { path = "../renderer" }
serde = { version = "1.0", features = ["derive"] }
