[package]
name = "renderer_web"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-std = "1"
cgmath = "~0.18.0"
console_error_panic_hook = "~0.1.7"
futures = { version = "~0.3.17", features = ["async-await"] }
gloo = "~0.4.0"
glow = { version = "~0.11.0" } 
js-sys = "~0.3.55"
ldraw = { path = "../../../ldraw" }
ldraw_ir = { path = "../../../ir" } 
ldraw_renderer = { path = "../../../renderer" }
reqwest = { version = "~0.11.8" }
wasm-bindgen = { version = "~0.2.78", features = ["serde-serialize"] }
wasm-bindgen-futures = "~0.4.28"
serde = { version = "1.0.80", features = ["derive"] }
serde_derive = "^1.0.59"
uuid = { version = "1", features = ["v4", "serde", "js"] }
viewer_common = { path = "../common" }

[dependencies.web-sys]
version = "~0.3.55"
features = [
    'CssStyleDeclaration',
    'Document',
    'Element',
    'Headers',
    'HtmlButtonElement',
    'HtmlCanvasElement',
    'HtmlDivElement',
    'HtmlSelectElement',
    'HtmlTextAreaElement',
    'MouseEvent',
    'Node',
    'Performance',
    'Touch',
    'TouchEvent',
    'TouchList',
    'UiEvent',
    'WebGlRenderingContext',
    'WheelEvent',
    'Window'
]

