name: Development CI

on:
  push:
    branches-ignore: 
    - main
  pull_request:
    branches-ignore:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cd tools/viewer/native
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Run tests
      run: cargo test --verbose
