name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        component: clippy
    - name: Build (native binaries)
      run: cargo build -p viewer_native -p ldr2img -p baker --verbose
    - name: Build (webassembly)
      env:
        RUSTFLAGS: --cfg=web_sys_unstable_apis
      run: cargo build -p viewer_web --target=wasm32-unknown-unknown --verbose
    - name: Lint
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
